config/routes.rb
Rails.application.routes.draw do
  root :to => "events#index"
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :events do
    post 'attend', on: :member
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  include SessionsHelper

  belongs_to :creator, class_name: 'User'
  has_and_belongs_to_many :attendees, class_name: 'User'
  validates :name, presence: true, uniqueness: true, length: { minimum: 5 }
  validates :location, presence: true, uniqueness: true, length: { minimum: 5, maximum: 50 }
  validates :date, presence: true

  scope :upcoming, -> { where('date >= ?', Time.zone.now) }
  scope :previous, -> { where('date < ?', Time.zone.now) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id
  has_and_belongs_to_many :attended_events, class_name: 'Event'

  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9]+\z/.freeze
  validates :username, presence: true, length: { maximum: 20, minimum: 5 }, format: { with: VALID_USERNAME_REGEX },
                       uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
# rubocop:disable Style/GuardClause

class ApplicationController < ActionController::Base
  include SessionsHelper

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find(session[:user_id])
  end

  private

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end
end

# rubocop:enable Style/GuardClause

app/controllers/events_controller.rb
# rubocop:disable Style/GuardClause

class EventsController < ApplicationController
  include EventsHelper
  before_action :logged_in_user, only: %i[new create]

  def index
    @events = Event.all
    @up_events = Event.upcoming
    @prev_events = Event.previous
  end

  def show
    @event = Event.find(params[:id])
    @attendants = @event.attendees
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_args)
    if @event.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy; end

  def attend
    @event = Event.find(params[:id])
    @event.attendees << current_user
    @event.save
    redirect_to root_path
  end

  private

  def event_args
    params.require(:event).permit(:name, :location, :date)
  end

  def require_login
    unless logged_in?
      flash[:error] = 'You must be logged in to access this section'
      redirect_to index
    end
  end
end

# rubocop:enable Style/GuardClause

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:session][:username])
    if user
      log_in user
      redirect_back_or root_path
    else
      flash.now[:notice] = 'You seem to not exist around here! Sign Up!'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @my_events = @user.events
    @attending_events = @user.attended_events
  end

  def create
    @user = User.new(user_args)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def user_args
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendants_helper.rb
module AttendantsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def attending?(event_id, user_id)
    found = nil
    Event.find(event_id).attendees.each do |attendant|
      found = attendant.id == user_id
    end
    found
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-6">
      <div class="h2">Upcoming Events</div>
      <% @up_events.each do |event| %>
        <%= render partial: 'share/eventcard', locals: {obj: event} %>
      <% end %>
    </div>
    <div class="col-12 col-lg-6">
      <div class="h2">Past Events</div>
      <% @prev_events.each do |event| %>
        <%= render partial: 'share/eventcard', locals: {obj: event} %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="col-12 col-lg-8 mt-20">
    <% if @event.errors.any? %>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <div class="alert alert-danger"><%= message %></div>
        <% end %>
      </ul>
    <% end %>
    <%= form_with model: @event do |event| %>
      <div class="form-group">
        <%= event.label :name %>
        <%= event.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= event.label :location %>
        <%= event.text_area :location, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= event.label :date %>
        <%= event.datetime_field :date, class: 'form-control' %>
      </div>
      <%= event.submit "Create Event", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="col-10 p-0">
    <%= render partial: 'share/eventcard', locals: {obj: @event} %>
  </div>
    <% if @attendants.length > 0 %>
      <h3>The following users are attending:</h3>
      <ul>
        <% @attendants.each do |attendee| %>
          <li><%= attendee.username %></li>
        <% end %>
      </ul>
    <% else %>
      <h3>No uses are attending this event just yet!</h3>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Ensemble</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('logo.png') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light static-top">
        <li class="nav-item">
          <%= image_tag "logo.png", style: 'height:40px;width:40px;' %>
        </li>
        <a class="navbar-brand red-me d-none d-md-block" href="#">Ensemble</a>
        <li class="nav-item"><%= link_to "All Events", root_path, class: 'nav-link' %></li>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "My Events", user_path(current_user), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "New Event", new_event_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "Log Out", logout_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li class="nav-item"><%= link_to "Log In", login_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "Sign Up", signup_path, class: 'nav-link' %></li>
        <% end %>
    </nav>
    <div class="container">
      <div class="col-12 p-0">
        <% if logged_in? %>
          <div class="h1 p-0">Hi, <%= User.find(current_user.id).username %>!</div>
        <% end %>
      </div>
    </div>
    <%= yield %>
</body>
</html>

app/views/share/_eventcard.html copy.erb
<% object.each do |obj| %>
  <div class="card my-2 my-lg-4">
    <div class="card-body">
        <h5 class="card-title red-me">
          <%= link_to obj.name, event_url(obj.id) %>
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">
          Location: <%= obj.location %>
        </h6>
        <h6 class="card-subtitle mb-2 text-muted">
          Date: <%= obj.date.strftime("%B %d, %Y | %l:%M %p") %>
        </h6>
        <h6 class="card-subtitle mb-2 text-muted">
          Created By: <%= User.find(obj.created_by).username %>
        </h6>
        <% if logged_in? %>
          <% if current_user.id == obj.created_by || attending?(obj.id, current_user.id) %>
            <h6 class="card-subtitle mb-2 text-muted">
              You already registered to attend this event!
            </h6>
          <% else %>
            <button type="button" class="btn btn-success">
              <%= link_to "I'm attending!", attend_path(user_id: current_user, event_id: obj.id), method: :post, class: 'mybutton' %>
            </button>
          <% end %>
        <% end %>
    </div>
  </div>
<% end %>

app/views/share/_eventcard.html.erb
<div class="card my-2 my-lg-4">
  <div class="card-body">
    <h5 class="card-title red-me">
      <%= link_to obj.name, event_url(obj.id) %>
    </h5>
    <h6 class="card-subtitle mb-2 text-muted">
      Location: <%= obj.location %>
    </h6>
    <h6 class="card-subtitle mb-2 text-muted">
      Date: <%= obj.date.strftime("%B %d, %Y | %l:%M %p") %>
    </h6>
    <h6 class="card-subtitle mb-2 text-muted">
      Created By: <%= User.find(obj.creator_id).username %>
    </h6>
    <% if logged_in? %>
      <% if current_user.id == obj.creator_id || attending?(obj.id, current_user.id) %>
        <h6 class="card-subtitle mb-2 text-muted">
          You already registered to attend this event!
        </h6>
      <% else %>
        <%= button_to 'I\'m attending!', attend_event_path(obj), method: :post, confirm: 'really?', class: "btn btn-success" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/share/_my-event.html.erb
<% object.each do |obj| %>
  <div class="card my-2 my-lg-4">
    <div class="card-body">
        <h5 class="card-title red-me">
          <%= link_to Event.find(obj.id).name, event_url(obj.id) %>
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">
          Location: <%= Event.find(obj.id).location %>
        </h6>
        <h6 class="card-subtitle mb-2 text-muted">
          Date: <%= Event.find(obj.id).date.strftime("%B %d, %Y | %l:%M %p") %>
        </h6>
        <h6 class="card-subtitle mb-2 text-muted">
          Created By: <%= User.find(Event.find(obj.id).creator_id).username %>
        </h6>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="col-8">
    <% if @user.errors.any? %>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <div class="alert alert-danger"><%= message %></div>
        <% end %>
        </ul>
      <% end %>
    <%= form_with model: @user do |user| %>
      <div class="form-group">
        <%= user.label :username %>
        <%= user.text_field :username, class: 'form-control' %>
      </div>
      <%= user.submit "Sign Up!", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-6">
      <div class="h2">Events Created By You:</div>
      <% @my_events.each do |event| %>
        <%= render partial: 'share/eventcard', locals: { obj: event } %>
      <% end %>
    </div>
    <div class="col-12 col-lg-6">
      <div class="h2">Events You're Attending:</div>
      <%= render partial: 'share/my-event', locals: { object: @attending_events } %>
    </div>
  </div>
</div>